### ISSUE TITLE
Chrome Store link is 404

### ISSUE THREAD

**Issue by jankcat** [Roystbeef/Cenafy#3]

**Comment by Roystbeef** [comment]
Just saw this in my inbox! Sorry for the late response.

Unfortunately the chrome web store took down the app because "it currently does not work or provide any functionality upon installation". I tried repealing the takedown after I confirmed the extension was still working, but never got a response  😢

**Comment by SecDevMatt** [comment]
Any update from the web store on this?

**Comment by LingleDev** [comment]
You can download a ZIP of the GitHub repo, and load an unpacked extension on chrome://extensions.

**Comment by Roystbeef** [comment]
[IT IS ALIVE](https://chrome.google.com/webstore/detail/cenafy/ndchmakhfaakbkhnkdgambadneloplnn/) <-- link to chrome store page
