### ISSUE TITLE
404 again

### ISSUE THREAD

**Issue by abso1utezer0** [Roystbeef/Cenafy#6]

**Comment by dev-hydrogen** [comment]
@Roystbeef ?

**Comment by Roystbeef** [comment]
Sorry for the delay in response - just got some free time to look into this. Turns out the extension was borked bc browsers have more stringent requirements for videos to autoplay (and rightfully so). https://github.com/Roystbeef/Cenafy/pull/7 has more details on this if you're curious.

I'm updating the chrome listing now, so it should be back up in a few days (I'll update & close this thread when it's live). Thanks for your patience! :)

**Comment by Roystbeef** [comment]
It's back up on https://chrome.google.com/webstore/detail/cenafy/ndchmakhfaakbkhnkdgambadneloplnn
